name: Generate GitHub Metrics

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  generate-metrics:
    runs-on: ubuntu-latest
    steps:
      - name: Generate metrics
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.svg
          token: ${{ secrets.GITHUB_TOKEN }}
          user: hugoalcala
          template: classic
          config_timezone: Europe/Madrid
          base: header, activity, community, repositories
          
          # Plugin para mostrar lenguajes
          plugin_languages: yes
          plugin_languages_sections: most-used
          plugin_languages_details: bytes-percentage, lines
          plugin_languages_analysis_timeout: 30

          # Para evitar errores de permisos, especifica que solo quieres tus repositorios p√∫blicos
          repositories_public: yes
          repositories: yes
          repositories_skipped: private
